amcl:
  ros__parameters:
    use_sim_time: False

    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link

    scan_topic: scan_filtered

    robot_model_type: differential

    set_initial_pose: True
    always_reset_initial_pose: True
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0

    tf_broadcast: True
    transform_tolerance: 1.0

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    # Beam skipping - ignores beams for which a majoirty of particles do not agree with the map
    # prevents correct particles from getting down weighted because of unexpected obstacles
    # such as humans
    do_beamskip: False
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    lambda_short: 0.1

    laser_model_type: likelihood_field
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: -1.0

    max_beams: 60

    max_particles: 25000
    min_particles: 6000

    pf_err: 0.05
    pf_z: 0.99

    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

    resample_interval: 1
    save_pose_rate: 0.5
    sigma_hit: 0.2

    update_min_a: 0.1
    update_min_d: 0.15

    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"
