bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link

    # groot monitoring will no longer be supported in humble https://github.com/ros-planning/navigation2/pull/2696
    # it sometimes crashes
    enable_groot_monitoring: False
    # groot_zmq_publisher_port: 1666
    # groot_zmq_server_port: 1667

    default_nav_to_pose_bt_xml: /navigate_w_recovery.xml
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False

    controller_frequency: 10.0

    # if velocity is below threshold value it is set to 0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001

    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker_plugin: "goal_checker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.25
      stateful: True # if stateful is true goal checker will not check if the xy position matches again once it is found to be true.

    controller_plugins: ["FollowPath"]
    FollowPath:
      # Shim controller first rotates robot in place to orientation of global path
      # and the switches to DWB - otherwise DWB won't turn in place, but with arc, which
      # is less optimal
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "dwb_core::DWBLocalPlanner"
      angular_dist_threshold: 0.4 # quite low value to avoid moving in arc
      forward_sampling_distance: 0.5
      rotate_to_heading_angular_vel: 1.5
      max_angular_accel: 4.0
      simulate_ahead_time: 1.0

      debug_trajectory_details: True

      min_vel_x: 0.0
      max_vel_x: 0.5
      acc_lim_x: 1.0
      decel_lim_x: -0.5
      min_speed_xy: 0.007
      max_speed_xy: 0.5

      max_vel_theta: 1.5
      min_speed_theta: 0.4
      acc_lim_theta: 4.0
      decel_lim_theta: -4.0

      min_vel_y: 0.0
      max_vel_y: 0.0
      acc_lim_y: 0.0
      decel_lim_y: 0.0

      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 20

      transform_tolerance: 1.0
      short_circuit_trajectory_evaluation: True

      trajectory_generator_name: "dwb_plugins::StandardTrajectoryGenerator"
      sim_time: 0.75 # low value to avoid slow movement near goal
      discretize_by_time: False
      linear_granularity: 0.05
      angular_granularity: 0.025

      # Critics used for scoring trajectories created by trajectory generator
      # Final score is a sum of critics' score
      critics:
        [
          "BaseObstacle",
          "ObstacleFootprint",

          "GoalAlign",
          "GoalDist",

          "PathAlign",
          "PathDist",

          "RotateToGoal",
          "Oscillation",
        ]

      BaseObstacle.scale: 0.02

      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      GoalDist.scale: 24.0

      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0

      xy_goal_tolerance: 0.1
      trans_stopped_velocity: 0.25
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False

      global_frame: odom
      robot_base_frame: base_link

      update_frequency: 5.0
      publish_frequency: 2.0

      width: 3
      height: 3
      resolution: 0.05

      always_send_full_costmap: True
      rolling_window: True

      footprint: "[[0.165, 0.145], [0.165, -0.145], [-0.165, -0.145], [-0.165, 0.145]]"

      plugins: ["static_layer", "voxel_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True # QoS setting; durability policy transient local, combined with any depth, provides functionality similar to that of latching publishers
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan_filtered
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 2.5
          raytrace_min_range: 0.0
          obstacle_max_range: 2.0
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55

  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False

      global_frame: map
      robot_base_frame: base_link

      update_frequency: 1.0
      publish_frequency: 1.0

      resolution: 0.05

      always_send_full_costmap: True
      track_unknown_space: True # if false, treats unknown space as free space, else as unknown space

      footprint: "[[0.165, 0.145], [0.165, -0.145], [-0.165, -0.145], [-0.165, 0.145]]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan_filtered
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 2.5
          raytrace_min_range: 0.0
          obstacle_max_range: 2.0
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55

  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

planner_server:
  ros__parameters:
    use_sim_time: False

    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.125 # tolerance for planning if unable to reach exact pose, in meters, for 2D node
      downsample_costmap: false # whether or not to downsample the map
      downsampling_factor: 1 # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: true # allow traveling in unknown space
      max_iterations: -1 # maximum total iterations to search for before failing
      max_on_approach_iterations: 1000 # maximum number of iterations to attempt to reach goal once in tolerance, 2D only
      max_planning_time: 2.0 # max time in s for planner to plan, smooth, and upsample. Will scale maximum smoothing and upsampling times based on remaining time after planning.
      smooth_path: true # Whether to smooth searched path
      motion_model_for_search: "MOORE" # 2D Moore, Von Neumann
      angle_quantization_bins: 72 # For SE2 node: Number of angle bins for search, must be 1 for 2D node (no angle search)
      minimum_turning_radius: 0.20 # For SE2 node & smoother: minimum turning radius in m of path / vehicle
      reverse_penalty: 2.1 # For Reeds-Shepp model: penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.20 # For SE2 node: penalty to apply if motion is changing directions, must be >= 0
      non_straight_penalty: 1.05 # For SE2 node: penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 1.3 # For SE2 node: penalty to apply to higher cost zones

      smoother:
        smoother:
          w_curve: 30.0 # weight to minimize curvature of path
          w_dist: 0.0 # weight to bind path to original as optional replacement for cost weight
          w_smooth: 30000.0 # weight to maximize smoothness of path
          w_cost: 0.025 # weight to steer robot away from collision and cost
          cost_scaling_factor: 10.0 # this should match the inflation layer's parameter

        # I do not recommend users mess with this unless they're doing production tuning
        optimizer:
          max_time: 0.10 # maximum compute time for smoother
          max_iterations: 500 # max iterations of smoother
          debug_optimizer: false # print debug info
          gradient_tol: 1.0e-10
          fn_tol: 1.0e-20
          param_tol: 1.0e-15
          advanced:
            min_line_search_step_size: 1.0e-20
            max_num_line_search_step_size_iterations: 50
            line_search_sufficient_function_decrease: 1.0e-20
            max_num_line_search_direction_restarts: 10
            max_line_search_step_expansion: 50

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    use_sim_time: False

    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1

    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0

    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

    # spin & backup
    simulate_ahead_time: 2.0

    # spin
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
